# Generated by Django 4.2.9 on 2024-09-09 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, verbose_name='Department')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=100, verbose_name='Office Name')),
                ('office_code', models.CharField(max_length=10, unique=True, verbose_name='Office Code')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('date_of_establishment', models.DateField(verbose_name='Date Of Establishment')),
                ('ceo', models.CharField(max_length=100, verbose_name='CEO')),
                ('staff_count', models.IntegerField(verbose_name='Staff Count')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
                'ordering': ['office_code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, verbose_name='Role')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
        ),
    ]
