# Generated by Django 5.0.6 on 2024-09-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_date',
            field=models.DateField(blank=True, null=True, verbose_name='Task Date'),
        ),
    ]
