# Generated by Django 5.0.6 on 2024-09-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_date',
        ),
    ]
