# Generated by Django 5.0.6 on 2024-09-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_remove_task_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_before',
            field=models.DateField(blank=True, null=True, verbose_name='Complete Before'),
        ),
    ]
