# Generated by Django 5.0.6 on 2024-09-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_completed_before'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed_before',
            new_name='complete_before',
        ),
    ]
