# Generated by Django 5.0.6 on 2024-09-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_rename_completed_before_task_complete_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='task_documents/', verbose_name='Document'),
        ),
    ]
