# Generated by Django 5.0.6 on 2024-09-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_remove_task_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
    ]
