# Generated by Django 5.0.6 on 2024-09-22 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0006_delete_task'),
        ('task', '0016_task_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='Attendance.employeepersonalinfo'),
        ),
    ]
