# Generated by Django 5.0.6 on 2024-09-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_title',
            field=models.CharField(default='Untitled Task', max_length=255, verbose_name='Task Title'),
        ),
    ]
