# Generated by Django 5.0.6 on 2024-09-21 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0006_delete_task'),
        ('task', '0019_task_task_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='Attendance.employeepersonalinfo'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('task', 'employee', 'rated_to')},
        ),
    ]
