# Generated by Django 4.2.9 on 2024-09-13 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Attendance', '0004_remove_employeesalarydeduction_lwf_amt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('personal', 'Personal Leave'), ('sick', 'Sick Leave'), ('vacation', 'Vacation'), ('casual', 'Casual Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('bereavement', 'Bereavement Leave'), ('public_holiday', 'Public Holiday Leave'), ('unpaid', 'Unpaid Leave'), ('medical', 'Medical Leave'), ('family', 'Family Leave')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_duration', models.CharField(choices=[('half_day', 'Half Day'), ('full_day', 'Full Day')], max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField()),
                ('office', models.BigIntegerField(blank=True, null=True, verbose_name='Office ID')),
                ('department', models.BigIntegerField(blank=True, null=True, verbose_name='Department ID')),
                ('role', models.BigIntegerField(blank=True, null=True, verbose_name='Role ID')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='supporting_documents/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='Attendance.employeepersonalinfo')),
            ],
        ),
    ]
