# Generated by Django 4.2.9 on 2024-09-13 07:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_remove_employeesalarydeduction_lwf_amt_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to='Attendance.employeepersonalinfo', verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved On'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_applied_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Leave Applied On'),
        ),
    ]
