# Generated by Django 4.2.9 on 2024-09-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
