# Generated by Django 4.2.9 on 2024-09-09 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True, verbose_name='Employee ID')),
                ('emp_name', models.CharField(max_length=100, null=True, verbose_name='Employee Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True, verbose_name='Gender')),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Employee Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the holiday')),
                ('reason', models.CharField(help_text='Reason for the holiday', max_length=255)),
                ('type', models.CharField(choices=[('FD', 'Full Day'), ('HD', 'Half Day')], default='FD', help_text='Type of the holiday (Full Day or Half Day)', max_length=2)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residential_address_verification', models.BooleanField(default=False, verbose_name='Residential Address Verification Done')),
                ('previous_employer_verification', models.BooleanField(default=False, verbose_name='Previous Employer Verification Done')),
                ('residential_address_gps', models.CharField(blank=True, max_length=100, null=True, verbose_name='Residential Address GPS Location')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='Attendance.employeepersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
                ('notice_period', models.BooleanField(default=False)),
                ('resigned', models.BooleanField(default=False)),
                ('terminated', models.BooleanField(default=False)),
                ('dead', models.BooleanField(default=False)),
                ('training_period', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='Attendance.employeepersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalaryEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Salary')),
                ('Bonus', models.BooleanField(default=False, verbose_name='Bonus Addition')),
                ('HRA', models.BooleanField(default=False, verbose_name='HRA Addition')),
                ('travel_claim_allowed', models.BooleanField(default=False, verbose_name='Travel Claim Allowed')),
                ('overtime_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Overtime Allowance')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeSalaryEarning', to='Attendance.employeepersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf', models.BooleanField(default=False, verbose_name='PF Deducted')),
                ('esic', models.BooleanField(default=False, verbose_name='ESIC Deducted')),
                ('pt', models.BooleanField(default=False, verbose_name='PT Deducted')),
                ('lwf', models.BooleanField(default=False, verbose_name='lwf Deducted')),
                ('tds', models.BooleanField(default=False, verbose_name='TDS Deducted')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeSalaryDeduction', to='Attendance.employeepersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Login', to='Attendance.employeepersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeJobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doj', models.DateField(null=True, verbose_name='Date of Joining')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('office', models.BigIntegerField(blank=True, null=True, verbose_name='Office ID')),
                ('department', models.BigIntegerField(blank=True, null=True, verbose_name='Department ID')),
                ('role', models.BigIntegerField(blank=True, null=True, verbose_name='Role ID')),
                ('qualifications', models.CharField(max_length=200, verbose_name='Qualifications')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Skills')),
                ('certifications', models.TextField(blank=True, null=True, verbose_name='Certifications')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Achievements')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_info', to='Attendance.employeepersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeHealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3, verbose_name='Blood Group')),
                ('mental_health', models.TextField(blank=True, null=True, verbose_name='Mental Health')),
                ('medical_health', models.TextField(blank=True, null=True, verbose_name='Medical Health')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to='Attendance.employeepersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(max_length=20, verbose_name='Bank Account Number')),
                ('pan_number', models.CharField(max_length=10, verbose_name='PAN Number')),
                ('aadhaar_number', models.CharField(max_length=10, null=True, verbose_name='Aadhaar Number')),
                ('aadhaar_linked_pan', models.BooleanField(default=False, verbose_name='Aadhaar Linked with PAN')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='Attendance.employeepersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_employer_details', models.TextField(verbose_name='Previous Employer Details')),
                ('previous_employer_contact_mobile', models.CharField(max_length=15, verbose_name='Previous Employer Contact Mobile')),
                ('previous_employer_contact_email', models.EmailField(max_length=254, verbose_name='Previous Employer Contact Email')),
                ('cibil_report', models.FileField(blank=True, null=True, upload_to='cibil_reports/', verbose_name='CIBIL Report')),
                ('pcc', models.FileField(blank=True, null=True, upload_to='pcc/', verbose_name='Police Clearance Certificate')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Attendance.employeepersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('whatsapp', models.CharField(max_length=15, null=True, verbose_name='whatsapp Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('residential_address', models.TextField(verbose_name='Residential Address')),
                ('work_location', models.CharField(max_length=100, verbose_name='Work Location')),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(max_length=15, verbose_name='Emergency Contact Phone')),
                ('family_contact_details', models.TextField(verbose_name='Family Contact Details')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='Attendance.employeepersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_salary_allowed', models.BooleanField(default=False, verbose_name='Advance Salary Allowed')),
                ('offer_letter_allowed', models.BooleanField(default=True, verbose_name='Offer Letter Allowed')),
                ('payslip_allowed', models.BooleanField(default=True, verbose_name='Payslip Allowed')),
                ('experience_letter_allowed', models.BooleanField(default=False, verbose_name='Experience/Relieving Letter Allowed')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeAccess', to='Attendance.employeepersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('check_in_location', models.CharField(blank=True, max_length=255, null=True)),
                ('check_out_location', models.CharField(blank=True, max_length=255, null=True)),
                ('hours_worked', models.CharField(blank=True, max_length=5, null=True)),
                ('overtime_hours', models.CharField(blank=True, max_length=5, null=True)),
                ('reason_for_absence', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('H', 'Half Day')], default='A', max_length=1)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('remark_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Attendance.employeepersonalinfo')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
