# Generated by Django 4.2.9 on 2024-09-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalarydeduction',
            name='BSCD',
            field=models.CharField(max_length=255, null=True, verbose_name='BSCD'),
        ),
        migrations.AddField(
            model_name='employeesalarydeduction',
            name='lwf_AMT',
            field=models.CharField(max_length=255, null=True, verbose_name='lwf_AMT'),
        ),
    ]
