# Generated by Django 4.2.9 on 2024-09-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_employeesalarydeduction_bscd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalaryearning',
            name='salary',
        ),
        migrations.AddField(
            model_name='employeesalaryearning',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='basic_salary'),
        ),
        migrations.AddField(
            model_name='employeesalaryearning',
            name='da',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='da'),
        ),
    ]
