# Generated by Django 4.2.9 on 2024-09-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_remove_employeesalaryearning_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalarydeduction',
            name='lwf_AMT',
        ),
        migrations.AddField(
            model_name='employeesalarydeduction',
            name='employee_lwf_AMT',
            field=models.CharField(max_length=255, null=True, verbose_name='employee_lwf_AMT'),
        ),
        migrations.AddField(
            model_name='employeesalarydeduction',
            name='employers_lwf_AMT',
            field=models.CharField(max_length=255, null=True, verbose_name='employers_lwf_AMT'),
        ),
    ]
