# Generated by Django 5.0.6 on 2024-09-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0005_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
